browser=chrome
baseUrl=https://demowebshop.tricentis.com
apiBaseUrl=https://thinking-tester-contact-list.herokuapp.com
timeout=10
visibilityTimeout=5
clickableTimeout=20
fluentTimeout=15
pollingInterval=500
platformName=Android
deviceName=emulator-5554
platformVersion=15
automationName=UIAutomator2
browserName=Chrome
chromedriverPath=src/main/resources/driver/chromedriver.exe